# Create a multi-stage build to reduce the size of the final image
FROM node:10.14.2-jessie as builder
WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
COPY server server
RUN yarn install && yarn build



FROM node:10.14.2-jessie
WORKDIR /app
COPY package*.json ./
ENV WEB_PORT=3005
RUN yarn install --production
COPY --from=builder /app/dist dist
#CMD esto corre el comando una ves levantado el contenedor.
CMD ["yarn", "start"]
